# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 70b240d1ad660576968a2bddbd89c2718d74880f7636913b97a2c7e184c9c625973b4cba51671a29087eb1ed8819bafb052adf1e07c1b1bd0d64880199924beb

test:
  secret_key_base: 933df7dffe72ce6d15893794b4a06ee5c25b057e2ee1ecd4785b4ff589c934c01e0bf46cbd0620b07b38a4c9feb2c64b5345b6d9ba811bf8fbb2df76386bb9bb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
